import type { ProjectShowcase } from './types';

/**
 * The fifth folder prints one full-height card per project. The first card is
 * the supplied AI new-media assignment and carries its hero, long board and
 * film as three slides inside one card. The third card is the supplied JD
 * campus campaign and opens its ten-page deck from the detail button. The
 * fourth card collects the WeChat features written for Henan TV, and each
 * slide opens its own article. The fifth card is the supplied set of
 * Kuaishou AI visuals: three campaign posters plus five reusable illustration
 * assets, each slide opening its own full-size file. The sixth card gathers the
 * 视频号 short films about Xinmi, and prints one 查看详情 button per link. The
 * seventh card collects
 * the campus competition entries and their awards as short animated clips, so
 * its numbered tabs sit along the top of the media frame and leave the picture
 * itself clear.
 */
export const projectShowcases: ProjectShowcase[] = [
  {
    id: 'blue-boom-new-media',
    code: '01',
    title: { zh: 'BooM 蓝莓小人 AI 新媒体作业', en: 'BooM Blueberry New Media Project' },
    kicker: { zh: '新媒体作业 · AI 形象与动态传播', en: 'New Media · AI IP & Motion' },
    summary: {
      zh: '以「Blue Boom 蓝莓气泡」为核心，先用 AI 生成角色概念，再统一毛绒质感、蓝莓头套、工装比例和表情状态，并把同一套 IP 继续延伸到品牌视觉与动态短片。',
      en: 'One AI-generated blueberry character developed into a complete new-media package: IP key visual, visual system and a 2:47 film.',
    },
    note: { zh: '涉及：AI 概念生成 · 品牌视觉延展 · 动态短片', en: 'AI concepts · Visual system · Motion film' },
    aside: {
      zh: '这张卡收纳完整作业：主视觉、品牌长图和短片都在同一个 16:9 画面里切换，短片可静音预览或开启声音播放。',
      en: 'One card, three supplied pieces. Switch between the key visual, the long board and the film; the film previews silently before sound is enabled.',
    },
    action: '查看详情',
    year: '2026',
    tags: ['AI生成', 'IP角色', '新媒体'],
    accent: '#4169E1',
    accentTo: '#2748B6',
    mediaKind: 'gallery',
    media: '/assets/projects/new-media/boom-ip-hero.jpg',
    mediaAlt: 'BooM 蓝莓小人 AI 新媒体作业',
    mediaPosition: '50% 50%',
    mediaFit: 'cover',
    mediaBadge: '16:9 主视觉',
    mediaItems: [
      {
        kind: 'image',
        src: '/assets/projects/new-media/boom-ip-hero.jpg',
        alt: 'BooM 蓝莓小人 IP 形象主视觉',
        position: '50% 50%',
        fit: 'cover',
        label: '主视觉',
        badge: '16:9 主视觉',
        action: '查看主视觉',
      },
      {
        kind: 'image',
        src: '/assets/projects/new-media/boom-brand-board.jpg',
        alt: 'Blue Boom 品牌视觉系统长图',
        position: '50% 0%',
        fit: 'scan',
        label: '品牌长图',
        badge: '纵向长图 · 自动扫视',
        action: '查看完整长图',
      },
      {
        kind: 'video',
        src: '/assets/projects/new-media/boom-new-media.mp4',
        poster: '/assets/projects/new-media/boom-ip-hero.jpg',
        alt: 'BooM 新媒体短片',
        position: '50% 50%',
        fit: 'contain',
        label: '短片',
        badge: '16:9 视频 · 02:47',
        action: '开启声音',
      },
    ],
  },
  {
    id: 'zhuanzhuan-cycling-accessories',
    code: '02',
    title: { zh: '转转骑行配件前端表达方案', en: 'Zhuanzhuan Cycling Accessories' },
    kicker: { zh: '转转实习 · 头盔 / 眼镜', en: 'Zhuanzhuan Internship' },
    summary: {
      zh: '从转转骑行头盔、眼镜的前端问题出发，梳理筛选维度、商品标题、商列标签与商品详情四个触点；横向盘点抖音、淘宝、京东、得物，再把已有标品属性映射到用户购买决策链路里。',
      en: 'Turning existing helmet and eyewear attributes into a practical front-end system across filters, titles, listing tags and product details.',
    },
    note: { zh: '涉及：标品属性梳理 · 竞品盘点 · 前端表达方案', en: 'Attributes · Benchmarking · Front-end expression' },
    aside: {
      zh: '现有问题、外部盘点和头盔/眼镜的前端设计都整理在原方案里；点击详情可以直接打开完整 PDF。',
      en: 'The original six-page proposal covers the audit, benchmark and helmet/eyewear design details.',
    },
    action: '查看完整 PDF',
    year: '2026',
    tags: ['转转实习', '商品运营', '前端表达'],
    accent: '#C45B3E',
    accentTo: '#8E3328',
    media: '/assets/projects/zhuanzhuan/zhuanzhuan-plan-preview.png',
    mediaAlt: '转转骑行配件前端表达方案首页预览',
    mediaPosition: '50% 0%',
    mediaFit: 'scan',
    mediaBadge: '方案 PDF · 6 页',
    detailPdf: '/assets/projects/zhuanzhuan/zhuanzhuan-internship.pdf',
  },
  {
    id: 'jd-campus-haircare',
    code: '03',
    title: { zh: '京东「洗护焕发青年力」', en: 'JD Campus Hair Care Campaign' },
    kicker: { zh: '京东实习 · 校园营销 IP', en: 'JD Internship · Campus IP' },
    summary: {
      zh: '从品类视角把洗护发接进学生成长轨迹，为「洗护焕发青年力」拆出发现、发言、发光三层 IP 内核；联动 15 个品牌落地 8 场校园快闪，学生用户同比 +42%。',
      en: 'A campus marketing IP for JD hair care: 15 brands, 8 campus pop-up markets and students up 42% year on year.',
    },
    note: { zh: '涉及：校园 IP · 品牌招商 · 全域资源 · 长效复盘', en: 'Campus IP · Brand recruitment · Resource rollout · Long-term review' },
    aside: {
      zh: '项目背景、三站战报、执行方法与复盘方法论都整理在这份 10 页分享里；点击详情可以直接打开完整 PDF。',
      en: 'Background, the three campus stops, the execution playbook and the review method, collected in one ten-page deck.',
    },
    action: '查看完整 PDF',
    year: '2026',
    tags: ['京东实习', '校园营销', '品牌运营'],
    accent: '#7C5CD6',
    accentTo: '#3F2A6E',
    media: '/assets/projects/jd/jd-campus-hero.png',
    mediaAlt: '京东超市洗护焕发青年力校园活动现场合集',
    mediaPosition: '50% 50%',
    mediaFit: 'cover',
    mediaBadge: '校园现场 · 三站落地',
    detailPdf: '/assets/projects/jd/jd-personal-care-final.pdf',
  },
  {
    id: 'henan-tv-wechat',
    code: '04',
    title: { zh: '河南卫视实习产出', en: 'Henan TV Internship Work' },
    kicker: { zh: '河南卫视实习 · 新媒体内容', en: 'Henan TV · New Media' },
    summary: {
      zh: '把文物、服饰、饮食、花卉这些看起来“冷”的选题，做成年轻人愿意转发的公众号内容：从找选题、查文物出处，到配图、排版和标题，五篇稿件都完整走了一遍。',
      en: 'Five WeChat features for Henan TV: museum pieces, historical dress, food history and flower motifs written for a young social audience.',
    },
    note: { zh: '涉及：选题策划 · 资料查证 · 图文编排', en: 'Topic planning · Research · Layout' },
    aside: {
      zh: '每篇稿件的原文封面都在卡片里，五个链接各有一个按钮，点哪个就直接跳到哪一篇「河南卫视」公众号原文。',
      en: 'Each slide is the original cover, and every article keeps its own button that opens that piece on the Henan TV account.',
    },
    action: '阅读公众号原文',
    year: '2023',
    tags: ['新媒体内容', '公众号', '文化科普'],
    accent: '#2C6BE0',
    accentTo: '#16307F',
    mediaKind: 'gallery',
    media: '/assets/projects/henan-tv/01-relics-memes.jpg',
    mediaAlt: '「别笑！我真的是文物，不是表情包……」公众号封面',
    mediaPosition: '50% 50%',
    mediaFit: 'cover',
    mediaBadge: '公众号原文 · 5 篇',
    // Every article keeps its own button instead of sharing one detail button.
    sourceList: true,
    mediaItems: [
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/01-relics-memes.jpg',
        alt: '「别笑！我真的是文物，不是表情包……」公众号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '文物',
        badge: '河南卫视 · 2023.08.24',
        action: '阅读公众号原文',
        href: 'https://mp.weixin.qq.com/s/BDYcDJvf5BQDEnZritXogQ',
        caption: '别笑！我真的是文物，不是表情包……',
        meta: '河南卫视公众号 · 2023.08.24',
        excerpt: '从景德镇「无语菩萨」到山西的东周猫爪金饰、广东的白切鸡玉雕，把博物馆里被网友做成表情包的文物盘点了一遍。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/02-dopamine-dressing.jpg',
        alt: '「20种颜色一起穿？多巴胺穿搭快乐到飞起！」公众号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '穿搭',
        badge: '河南卫视 · 2023.07.06',
        action: '阅读公众号原文',
        href: 'https://mp.weixin.qq.com/s/2_z7ldm9-CBHD8hDmwBM0A',
        caption: '20种颜色一起穿？“多巴胺穿搭”快乐到飞起！',
        meta: '河南卫视公众号 · 2023.07.06',
        excerpt: '借夏天最热的「多巴胺穿搭」，回溯秦汉唐宋明清的服饰配色：兵马俑身上的「中国紫」、《捣练图》里的红蓝撞色。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/03-lotus-love.jpg',
        alt: '「莲花还能用来示爱？是在下输了！」公众号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '莲花',
        badge: '河南卫视 · 2023.08.05',
        action: '阅读公众号原文',
        href: 'https://mp.weixin.qq.com/s/5wLwcv-JcRsnjqeNpD-JJg',
        caption: '莲花还能用来示爱？是在下输了！',
        meta: '河南卫视公众号 · 2023.08.05',
        excerpt: '从新石器时代的莲瓣纹陶器讲到明清缠枝莲，再落到《诗经》与《爱莲说》里的爱情和君子之意。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/04-two-meals.jpg',
        alt: '「古人一日两餐，究竟少了哪顿饭？」公众号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '两餐',
        badge: '河南卫视 · 2023.07.28',
        action: '阅读公众号原文',
        href: 'https://mp.weixin.qq.com/s/kis3VBeqClknLBHHiKAtkg',
        caption: '古人一日两餐，究竟少了哪顿饭？',
        meta: '河南卫视公众号 · 2023.07.28',
        excerpt: '从商代的「大食」「小食」写到民国，讲清一日两餐是怎么被粮食产量、漕运和农时一点点推到一日三餐的。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/05-new-logo.jpg',
        alt: '「河大卫邀请河大卫TV加入群聊」公众号封面',
        position: '50% 50%',
        fit: 'cover',
        label: 'LOGO',
        badge: '河南卫视 · 2023.08.01',
        action: '阅读公众号原文',
        href: 'https://mp.weixin.qq.com/s/-t9CvAI0dfHn2T07NqwH0Q',
        caption: '河大卫邀请“河大卫TV”加入群聊！',
        meta: '河南卫视公众号 · 2023.08.01',
        excerpt: '河南卫视新媒体 LOGO 焕新：在台标基础上提炼出「HN」小象造型，用群聊口吻完成这次发布。',
      },
    ],
  },
  {
    id: 'kuaishou-ai-visuals',
    code: '05',
    title: { zh: '快手技术品牌 AI 视觉', en: 'Kuaishou Tech Brand AI Visuals' },
    kicker: { zh: '快手实习 · 技术品牌内容', en: 'Kuaishou Internship · Tech Brand' },
    summary: {
      zh: '把技术会议和节日节点做成一整套 AI 视觉：NeurIPS 2025 与 AAAI 2026 的会议海报、丙午马年的新春主视觉，再加上星空、发光树和 3D 购物场景这些可以反复复用的插画素材。',
      en: 'One AI visual system for the tech brand: conference posters for NeurIPS 2025 and AAAI 2026, a Lunar New Year key visual and reusable illustration assets.',
    },
    note: { zh: '涉及：AI 出图 · 会议海报 · 节日主视觉 · 素材沉淀', en: 'AI visuals · Conference posters · Festival key visual · Asset library' },
    aside: {
      zh: '八张成图收在同一张卡里：三张海报负责会议与节点传播，五张插画沉进日常内容；切换下方编号就能逐张看，点「查看大图」直接打开原图。',
      en: 'Eight finished visuals in one card: three campaign posters and five reusable illustrations. Switch with the numbered tabs and the detail button opens the original file.',
    },
    action: '查看大图',
    year: '2026',
    tags: ['快手实习', 'AI 出图', '技术品牌'],
    accent: '#F4581F',
    accentTo: '#A6340B',
    mediaKind: 'gallery',
    media: '/assets/projects/kuaishou/01-new-year-horse.jpg',
    mediaAlt: '快手技术「马年大吉」新春主视觉',
    mediaPosition: '50% 50%',
    mediaFit: 'cover',
    mediaBadge: 'AI 视觉 · 8 张',
    mediaItems: [
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/01-new-year-horse.jpg',
        alt: '快手技术「马年大吉」新春主视觉',
        position: '50% 50%',
        fit: 'cover',
        label: '新春',
        badge: '马年新春主视觉',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/02-aaai-2026-singapore.jpg',
        alt: '快手技术 AAAI 2026 会议海报',
        position: '50% 50%',
        fit: 'contain',
        label: 'AAAI',
        badge: 'AAAI 2026 新加坡',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/03-neurips-2025-san-diego.jpg',
        alt: '快手技术 NeurIPS 2025 会议海报',
        position: '50% 50%',
        fit: 'contain',
        label: 'NeurIPS',
        badge: 'NeurIPS 2025',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/04-star-boat.jpg',
        alt: '星空与湖面小船的 AI 插画素材',
        position: '50% 50%',
        fit: 'cover',
        label: '星空',
        badge: 'AI 素材 · 星空小船',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/05-glow-tree.jpg',
        alt: '夜色中发光树的 AI 插画素材',
        position: '50% 50%',
        fit: 'cover',
        label: '发光树',
        badge: 'AI 素材 · 发光树',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/06-cart-3d.jpg',
        alt: '购物车与商品的 3D 插画素材',
        position: '50% 50%',
        fit: 'cover',
        label: '购物车',
        badge: 'AI 素材 · 购物车',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/07-toolbox-3d.jpg',
        alt: '装满界面卡片的 3D 工具箱素材',
        position: '50% 50%',
        fit: 'cover',
        label: '工具箱',
        badge: 'AI 素材 · 工具箱',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/kuaishou/08-robot-shopping.jpg',
        alt: '机器人在超市采购的 3D 插画素材',
        position: '50% 50%',
        fit: 'cover',
        label: '机器人',
        badge: 'AI 素材 · 机器人',
        action: '查看大图',
      },
    ],
    // The plan the visuals belong to, plus the four technical pieces they ran
    // with: two 技术沙龙 write-ups, a NeurIPS 2025 paper story and the ICCV
    // 2025 finalist announcement.
    links: [
      {
        label: '小红书运营规划',
        headline: '2026 快手技术小红书年度运营规划',
        href: '/assets/projects/kuaishou/kuaishou-xiaohongshu-plan-2026.pdf',
        action: '查看策划案',
      },
      {
        label: 'KMP 沙龙',
        headline: '快手技术沙龙圆满落幕：共探 KMP 落地与 AI 融合新未来！',
        href: 'https://mp.weixin.qq.com/s/91OBQcyL5LPOn9KbMg77IA',
      },
      {
        label: 'NeurIPS 论文',
        headline: 'NeurIPS 2025 | 让扩散模型“评价”自己：中科院与快手可灵团队提出隐式奖励建模新范式',
        href: 'https://mp.weixin.qq.com/s/rm3R5qWY4vgf85L0pcBpOw',
      },
      {
        label: '推荐沙龙',
        headline: '快手技术沙龙举办：生成式推荐系统如何重构搜推广？',
        href: 'https://mp.weixin.qq.com/s/Jz7sDbB-uBfd5fu9Xnis9g',
      },
      {
        label: 'ICCV 论文',
        headline: '可灵团队论文 ReCamMaster 入选 ICCV 2025 Best Paper Finalist',
        href: 'https://mp.weixin.qq.com/s/AM6y6-zav4taW7j72urk_w',
      },
    ],
  },
  {
    id: 'henan-tv-channels',
    code: '06',
    title: { zh: '新密市融媒体实习', en: 'Henan TV Channels Short Films' },
    kicker: { zh: '河南卫视实习 · 视频号内容', en: 'Henan TV · WeChat Channels' },
    summary: {
      zh: '把新密的城市日常剪成视频号短片：青春街头、文明城市公益、银基摩天轮、旧味小吃、市井人物和元宵节去处，六条片子把文旅节点、城市形象和小城故事几种选题都跑了一遍。',
      en: 'Six 视频号 city films for Xinmi: a youth street piece, a civic campaign, a theme-park landmark, a street-food memory, a market character and a Lantern Festival guide.',
    },
    note: { zh: '涉及：选题策划 · 短视频文案 · 剪辑包装', en: 'Topic planning · Short-video copy · Editing' },
    aside: {
      zh: '六条短片都在卡片里，每条都有自己的封面和文案；想直接看哪一条，就点它对应的「查看详情」。',
      en: 'Six films, each with its own cover and copy. Every link keeps its own 查看详情 button.',
    },
    action: '查看详情',
    year: '2023',
    tags: ['视频号', '短视频', '城市文旅'],
    accent: '#12857C',
    accentTo: '#0A4B49',
    mediaKind: 'gallery',
    media: '/assets/projects/henan-tv/06-xinmi-youth.jpg',
    mediaAlt: '「每一刻都像永远，24岁离18和30岁一样近」视频号封面',
    mediaPosition: '50% 42%',
    mediaFit: 'cover',
    mediaBadge: '视频号短片 · 6 条',
    sourceList: true,
    mediaItems: [
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/06-xinmi-youth.jpg',
        alt: '「每一刻都像永远，24岁离18和30岁一样近」视频号封面',
        position: '50% 42%',
        fit: 'cover',
        label: '青春',
        badge: '厮跟着到新密 · 2023.02.25',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/AEV6oYuo3w',
        caption: '每一刻都像永远，24岁离18和30岁一样近',
        meta: '厮跟着到新密 · 2023.02.25',
        excerpt: '城市短片：24 岁离 18 岁和 30 岁一样近，把新密的街头日常剪成一段关于「青春的样子」的记录。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/07-xinmi-water.jpg',
        alt: '「爱惜生命之源，“关”住滴滴点点」视频号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '文明',
        badge: '厮跟着到新密 · 2023.02.28',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/Al9M0I6mrT',
        caption: '爱惜生命之源，“关”住滴滴点点',
        meta: '厮跟着到新密 · 2023.02.28',
        excerpt: '文明城市公益短片：用「关」住滴滴点点讲日常节水，接下「创建文明城市 · 建设美好家园」的新密城市形象。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/08-xinmi-wheel.jpg',
        alt: '「谁的童年没有一座能高空俯瞰的摩天轮呢」视频号封面',
        position: '50% 45%',
        fit: 'cover',
        label: '摩天轮',
        badge: '厮跟着到新密 · 2023.02.09',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/ANONDH7lEA',
        caption: '谁的童年没有一座能高空俯瞰的摩天轮呢？',
        meta: '厮跟着到新密 · 2023.02.09',
        excerpt: '春季文旅选题：以银基国际旅游度假区的摩天轮为切口，把童年记忆做成「这个春天再去坐一次」的出发理由。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/09-xinmi-flatbread.jpg',
        alt: '「新密旧味｜土掉渣饼陪伴了多少新密人的学生时代」视频号封面',
        position: '50% 50%',
        fit: 'cover',
        label: '旧味',
        badge: '厮跟着到新密 · 2023.01.07',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/AkUXc7qn0h',
        caption: '新密旧味｜土掉渣饼陪伴了多少新密人的学生时代',
        meta: '厮跟着到新密 · 2023.01.07',
        excerpt: '「新密旧味」系列：把土掉渣饼和学生时代的记忆放在一起，讲一种小吃怎么成为一代人的共同味道。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/10-xinmi-fishmonger.jpg',
        alt: '「我就是个卖鱼的」视频号封面',
        position: '50% 42%',
        fit: 'cover',
        label: '卖鱼',
        badge: '厮跟着到新密 · 2023.02.02',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/Av8UDrj1CQ',
        caption: '我就是个卖鱼的',
        meta: '厮跟着到新密 · 2023.02.02',
        excerpt: '跟着《狂飙》的热度做的小城人物短片：一句「我就是个卖鱼的」，把新密的市井气和人间烟火讲给同城的人听。',
      },
      {
        kind: 'image',
        src: '/assets/projects/henan-tv/11-xinmi-lantern.jpg',
        alt: '「元宵节去哪儿玩？看这一个视频就够了」视频号封面',
        position: '50% 42%',
        fit: 'cover',
        label: '元宵',
        badge: '厮跟着到新密 · 2023.02.03',
        action: '查看详情',
        href: 'https://weixin.qq.com/sph/AyhU68ld9M',
        caption: '元宵节去哪儿玩？看这一个视频就够了',
        meta: '厮跟着到新密 · 2023.02.03',
        excerpt: '节日节点短片：元宵节去哪儿玩，一条视频把新密的节日去处、路线和玩法讲清楚。',
      },
    ],
  },
  {
    id: 'campus-awards',
    code: '07',
    title: { zh: '参赛作品与获奖记录', en: 'Competition Entries & Awards' },
    kicker: { zh: '校园创作 · 参赛获奖', en: 'Campus Work · Competitions' },
    summary: {
      zh: '把校园作品一件件送进比赛，卡里放的是各自的参赛片段：新闻采访《我的外卖去哪了》、防震减灾科普讲解《地震来了，是该躲还是该逃？》，以及讲文物故事、科学传播、思政微电影和 MG 动画等赛道的九件作品；其中天津市大学生思政讲课大赛拿到校一等奖，中广视讯杯获鼓励奖。',
      en: 'Nine campus pieces entered in Tianjin competitions — a news report, science talks, a relic-history video and an ideology micro-film — including a first prize in the university round of the ideological lecture contest.',
    },
    note: { zh: '涉及：选题策划 · 出镜讲解 · 拍摄剪辑 · 参赛获奖', en: 'Topic planning · On-camera delivery · Editing · Awards' },
    aside: {
      zh: '九件参赛作品按编号排在一起，画面本身就是会动的片段；点画面、点「查看大图」，或点侧边对应的作品按钮，都能把这一段放大来看。',
      en: 'Nine competition entries in one card, each playing as a short clip. Click the picture, the detail button or the entry button beside it to open that clip larger.',
    },
    action: '查看大图',
    year: '2024',
    tags: ['参赛获奖', '短视频', '科普传播'],
    accent: '#C63A2A',
    accentTo: '#7E1810',
    mediaKind: 'gallery',
    media: '/assets/projects/awards/01-food-delivery-news.gif',
    mediaAlt: '《我的外卖去哪了》新闻采访视频片段',
    mediaPosition: '50% 50%',
    mediaFit: 'cover',
    mediaTabsPosition: 'top',
    mediaItems: [
      {
        kind: 'image',
        src: '/assets/projects/awards/01-food-delivery-news.gif',
        alt: '《我的外卖去哪了》新闻采访视频片段',
        position: '50% 50%',
        fit: 'cover',
        label: '新闻采访',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/02-ideological-lecture-first-prize.gif',
        alt: '天津市大学生思政讲课大赛校一等奖片段',
        position: '50% 50%',
        fit: 'cover',
        label: '思政讲课',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/03-relic-history-video.gif',
        alt: '讲文物历史故事视频大赛片段',
        position: '50% 50%',
        fit: 'cover',
        label: '文物故事',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/04-ideological-microfilm.gif',
        alt: '我心中的思政课微电影大赛片段',
        position: '50% 50%',
        fit: 'cover',
        label: '微电影',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/05-tianjin-science-communication.gif',
        alt: '天津市科学传播视频大赛片段',
        position: '50% 50%',
        fit: 'cover',
        label: '科学传播',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/06-science-video-mg-animation.gif',
        alt: '天津市科普视频大赛 MG 动画片段',
        position: '50% 50%',
        fit: 'cover',
        label: 'MG动画',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/07-earthquake-science-talk.jpg',
        alt: '2024 年天津市防震减灾科普讲解大赛画面',
        position: '50% 50%',
        fit: 'cover',
        label: '防震减灾',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/08-zhongguangshixun-encouragement.gif',
        alt: '天津市中广视讯杯视频大赛鼓励奖片段',
        position: '50% 50%',
        fit: 'cover',
        label: '中广视讯',
        action: '查看大图',
      },
      {
        kind: 'image',
        src: '/assets/projects/awards/09-graduation-exhibition-review.jpg',
        alt: '数智传媒与设计艺术学院毕业设计展现场',
        position: '50% 50%',
        fit: 'cover',
        label: '毕业设计',
        action: '查看大图',
      },
    ],
  },
];

/**
 * Every still the fifth folder prints, preloaded with the rest of the site.
 * Animated clips are heavy, so they load with their own card instead of
 * holding up the first pass.
 */
export const projectShowcaseAssetUrls: readonly string[] = [
  ...new Set(projectShowcases.flatMap((item) => [
    item.media,
    ...(item.mediaItems ?? [])
      .filter((media) => media.kind === 'image')
      .map((media) => media.src),
  ]).filter((source) => !/\.gif$/i.test(source))),
];
